"""
Babel IGP Renderer

Generates BIRD Babel protocol configuration for IGP underlay.
"""
from jinja2 import Template


BABEL_TEMPLATE = """# Babel IGP Configuration - Auto-generated by MoeNet Agent
# DO NOT EDIT MANUALLY

protocol babel babel_igp {
    # Run on WG IGP mesh interfaces and dummy0 (for DN42 loopback)
    interface "wg-igp-*", "dummy0" {
        type wired;
        hello interval 4 s;
        update interval 16 s;
    };
    
    ipv6 {
        # Only accept and announce /128 loopback addresses
        import filter {
            if net.len = 128 then accept;
            reject;
        };
        export filter {
            if net.len = 128 then accept;
            reject;
        };
    };
}
"""


IBGP_PEER_TEMPLATE = """# iBGP Peer: {{ peer_name }}
# Auto-generated by MoeNet Agent

protocol bgp ibgp_{{ peer_name | replace('.', '_') | replace('-', '_') }} from dn42_internal {
    neighbor {{ peer_loopback }} as {{ asn }};
    description "iBGP to {{ peer_name }}";
{% if is_rr_client %}
    rr client;
{% endif %}
}
"""


def render_babel_config() -> str:
    """Render Babel IGP configuration.
    
    Returns:
        BIRD Babel protocol configuration
    """
    return BABEL_TEMPLATE


def render_ibgp_peer(
    peer_name: str,
    peer_loopback: str,
    asn: int = 4242420998,
    is_rr_client: bool = False,
) -> str:
    """Render iBGP peer configuration using loopback address.
    
    Args:
        peer_name: Peer node name
        peer_loopback: Peer loopback IPv6 address
        asn: Local AS number
        is_rr_client: Whether this peer is an RR client
        
    Returns:
        BIRD iBGP peer configuration
    """
    template = Template(IBGP_PEER_TEMPLATE)
    return template.render(
        peer_name=peer_name,
        peer_loopback=peer_loopback,
        asn=asn,
        is_rr_client=is_rr_client,
    )
