"""
MoeNet DN42 Agent - iBGP BIRD Template

Generates BIRD configuration for iBGP sessions with RR and other nodes.
"""
IBGP_TEMPLATE = """
# iBGP Configuration for {{ local_name }}
# Auto-generated by MoeNet Agent - DO NOT EDIT
# Uses dn42_internal template defined in main bird.conf

{% for peer in peers %}
protocol bgp ibgp_{{ peer.name | replace('.', '_') | replace('-', '_') }} from dn42_internal {
    neighbor {{ peer.ipv6 if prefer_v6 and peer.ipv6 else peer.ipv4 }} as {{ peer.asn }};
    description "iBGP {{ peer.name }}";
{% if peer.is_rr_client and is_rr %}
    rr client;
{% endif %}
}
{% endfor %}
"""


def render_ibgp_config(config: dict, prefer_v6: bool = True) -> str:
    """Render iBGP configuration for BIRD.
    
    Args:
        config: iBGP configuration from control-plane API
        prefer_v6: Prefer IPv6 for peering if available
        
    Returns:
        BIRD protocol configuration string
    """
    from jinja2 import Template
    
    template = Template(IBGP_TEMPLATE)
    return template.render(
        local_name=config.get("local_name", "unknown"),
        local_asn=config.get("local_asn", 4242420998),
        is_rr=config.get("is_rr", False),
        peers=config.get("peers", []),
        prefer_v6=prefer_v6,
    )
