"""
iBGP Configuration Renderer

Generates BIRD iBGP peer configurations for DN42 internal routing.
Works with mesh_sync to provide complete IGP + iBGP underlay.
"""
from jinja2 import Template


IBGP_PEER_TEMPLATE = """# iBGP Peer: {{ peer_name }}
# Auto-generated by MoeNet Agent
# Uses loopback address for stability (Babel provides reachability)
# DO NOT EDIT MANUALLY

protocol bgp ibgp_{{ peer_name | replace('.', '_') | replace('-', '_') }} from dn42_internal {
    neighbor {{ peer_loopback }} as {{ asn }};
    description "iBGP to {{ peer_name }}";
}
"""


def render_ibgp_peer(
    peer_name: str,
    peer_loopback: str,
    asn: int = 4242420998,
) -> str:
    """Render iBGP peer configuration using loopback address.
    
    Args:
        peer_name: Peer node name
        peer_loopback: Peer loopback IPv6 address
        asn: Local AS number
        
    Returns:
        BIRD iBGP peer configuration
    """
    template = Template(IBGP_PEER_TEMPLATE)
    return template.render(
        peer_name=peer_name,
        peer_loopback=peer_loopback,
        asn=asn,
    )
