"""
OSPFv3 IGP Renderer

Generates BIRD OSPFv3 neighbor configuration for PTMP mode.
Uses unicast hellos instead of multicast for WireGuard compatibility.
"""
from jinja2 import Template


OSPF_NEIGHBORS_TEMPLATE = """# OSPFv3 PTMP Neighbors - Auto-generated by MoeNet Agent
# DO NOT EDIT MANUALLY
# These neighbors use unicast OSPFv3 hellos (no multicast needed)

neighbors {
{% for peer in peers %}
    {{ peer.link_local }};  # {{ peer.name }} (node_id={{ peer.node_id }})
{% endfor %}
};
"""


def render_ospf_neighbors(peers: list[dict]) -> str:
    """Render OSPFv3 PTMP neighbors configuration.
    
    Args:
        peers: List of peer dictionaries with keys:
            - name: Peer node name
            - node_id: Peer node ID
            - link_local: Peer link-local IPv6 address (e.g., fe80::1)
            
    Returns:
        BIRD OSPFv3 neighbors configuration
    """
    template = Template(OSPF_NEIGHBORS_TEMPLATE)
    return template.render(peers=peers)
