"""
WireGuard Mesh Network Renderer

Generates WireGuard IGP mesh tunnels between DN42 nodes for Babel IGP underlay.
"""
import subprocess
from pathlib import Path
from jinja2 import Template


WG_MESH_TEMPLATE = """# WireGuard IGP Mesh - Auto-generated by MoeNet Agent
# Peer: {{ peer_name }}
# DO NOT EDIT MANUALLY

[Interface]
PrivateKey = {{ private_key }}
ListenPort = {{ listen_port }}

[Peer]
# {{ peer_name }}
PublicKey = {{ peer_public_key }}
{% if peer_endpoint %}
Endpoint = {{ peer_endpoint }}:{{ peer_port }}
{% endif %}
AllowedIPs = fe80::/64, {{ peer_loopback }}/128
PersistentKeepalive = 25
"""


def generate_wg_keypair() -> tuple[str, str]:
    """Generate a new WireGuard key pair.
    
    Returns:
        Tuple of (private_key, public_key)
    """
    private_key = subprocess.run(
        ["wg", "genkey"],
        capture_output=True,
        text=True,
        check=True
    ).stdout.strip()
    
    public_key = subprocess.run(
        ["wg", "pubkey"],
        input=private_key,
        capture_output=True,
        text=True,
        check=True
    ).stdout.strip()
    
    return private_key, public_key


def get_or_create_mesh_key(key_path: Path) -> tuple[str, str]:
    """Get existing mesh key or create new one.
    
    Args:
        key_path: Path to store/load the private key
        
    Returns:
        Tuple of (private_key, public_key)
    """
    if key_path.exists():
        private_key = key_path.read_text().strip()
        public_key = subprocess.run(
            ["wg", "pubkey"],
            input=private_key,
            capture_output=True,
            text=True,
            check=True
        ).stdout.strip()
        return private_key, public_key
    
    # Generate new key
    private_key, public_key = generate_wg_keypair()
    
    # Save private key
    key_path.parent.mkdir(parents=True, exist_ok=True)
    key_path.write_text(private_key)
    key_path.chmod(0o600)
    
    return private_key, public_key


def render_mesh_interface(
    interface_name: str,
    private_key: str,
    listen_port: int,
    node_id: int,
    peer_name: str,
    peer_public_key: str,
    peer_node_id: int,
    peer_loopback: str,
    peer_endpoint: str | None = None,
    peer_port: int = 51820,
) -> str:
    """Render WireGuard mesh interface configuration.
    
    Args:
        interface_name: WG interface name (e.g., wg-igp-1)
        private_key: Local WG private key
        listen_port: Local WG listen port
        node_id: Local node ID (for link-local addressing)
        peer_name: Peer node name
        peer_public_key: Peer WG public key
        peer_node_id: Peer node ID
        peer_loopback: Peer loopback IPv6 address
        peer_endpoint: Peer public endpoint (IP or hostname)
        peer_port: Peer WG port
        
    Returns:
        WireGuard configuration string
    """
    template = Template(WG_MESH_TEMPLATE)
    return template.render(
        private_key=private_key,
        listen_port=listen_port,
        node_id=node_id,
        peer_name=peer_name,
        peer_public_key=peer_public_key,
        peer_node_id=peer_node_id,
        peer_loopback=peer_loopback,
        peer_endpoint=peer_endpoint,
        peer_port=peer_port,
    )
